In [27]:
import numpy as np
def normalize_comparation(M):
    """Function for normalizing the pairwise comparison matrix"""
    # sum the elements within the same column
    sumCol = M.sum(axis = 0) # axis 0 = kolom, 1 = baris
    norm = M / sumCol
    return norm


def weight(M):
    """Function for calculating the weight of the criteria or
    alternatives"""
    # calculate the average value of each row
    return np.mean(M, axis=1)


def validity_check(M,W):
    """Function for checking the validity of the weights"""
    n = len(M)
    RI = {
    2: 0.00, 3: 0.58, 4: 0.90, 5: 1.12, 6: 1.24, 7: 1.32, 8: 1.41, 9:
    1.45,10: 1.51, 11: 1.53, 12: 1.54, 13: 1.56, 14: 1.57
    }   
    # calculate CV
    CV = M @ W / W # @ operator perform matrix multiplication according to the mathematical rules
    print(f"CV: {CV}\n")
    # calculate eigenvalue
    eigen = np.mean(CV)
    print(f"Eigen: {eigen}\n")
    # find RI value
    print(f"RI: {RI[n]}\n")
    # calculate CI
    CI = (eigen - n) / (n - 1)
    print(f"CI: {CI}\n")
    # calculate CR
    CR = CI / RI[n]
    print(f"CR: {CR}\n")
    if CR <= 0.1:
        print("Weight is valid!\n")
    else:
        print("Weight is invalid!\n")

def final_weight(W_alt, W_crit):
    """Function for calculating the final weight of the alternatives"""
    # multiplies the alternative weights with the criteria weights according to the mathematical rules
    W_fin = W_alt.T @ W_crit
    return W_fin


In [28]:
# alternatives
A = ["Yamaha","Honda","Suzuki","Kawasaki"]
print("=== Criteria ===")
# pairwise comparison matrix of the criteria
# order: style, reliability, fuel economy
PCMc = np.array([
[1, 1/2, 3],
[2, 1, 4],
[1/3, 1/4, 1]
])

print(f"Pairwise comparison matrix: \n {PCMc}\n")
# normalization
PCMc_norm = normalize_comparation(PCMc)
print(f"Normalized pairwise comparison matrix: \n {PCMc_norm}\n")
# calculate weight
Wc = weight(PCMc_norm)
print(f"Criteria weight: \n {Wc}\n")
# check weight validity
validity_check(PCMc,Wc)

=== Criteria ===
Pairwise comparison matrix: 
 [[1.         0.5        3.        ]
 [2.         1.         4.        ]
 [0.33333333 0.25       1.        ]]

Normalized pairwise comparison matrix: 
 [[0.3        0.28571429 0.375     ]
 [0.6        0.57142857 0.5       ]
 [0.1        0.14285714 0.125     ]]

Criteria weight: 
 [0.3202381  0.55714286 0.12261905]

CV: [3.01858736 3.02991453 3.00647249]

Eigen: 3.01832479413957

RI: 0.58

CI: 0.009162397069784944

CR: 0.015797236327215424

Weight is valid!



In [29]:
print("=== Style ===")
# pairwise comparison matrix of style for each alternative
# order: yamaha, honda, suzuki, kawasaki
PCMs= np.array([
[1, 1/2, 2, 1/3],
[2, 1, 3, 1/2],
[1/2, 1/3, 1, 1/4],
[3, 2, 4, 1]
])
print(f"Pairwise comparison matrix: {PCMs}\n")
# normalization
PCMs_norm = normalize_comparation(PCMs)
print(f"Normalized pairwise comparison matrix: {PCMs_norm}\n")
# calculate weight
Ws = weight(PCMs_norm)
print(f"Weight: {Ws}\n")
# check weight validity
validity_check(PCMs,Ws)

=== Style ===
Pairwise comparison matrix: [[1.         0.5        2.         0.33333333]
 [2.         1.         3.         0.5       ]
 [0.5        0.33333333 1.         0.25      ]
 [3.         2.         4.         1.        ]]

Normalized pairwise comparison matrix: [[0.15384615 0.13043478 0.2        0.16      ]
 [0.30769231 0.26086957 0.3        0.24      ]
 [0.07692308 0.08695652 0.1        0.12      ]
 [0.46153846 0.52173913 0.4        0.48      ]]

Weight: [0.16107023 0.27714047 0.0959699  0.4658194 ]

CV: [4.01597107 4.04163398 4.01521752 4.05133544]

Eigen: 4.03103950215422

RI: 0.9

CI: 0.010346500718073415

CR: 0.011496111908970461

Weight is valid!



In [30]:
print("=== Reliability ===")
# pairwise comparison matrix of reliability for each alternative
# order: yamaha, honda, suzuki, kawasaki
PCMr= np.array([
[1, 1/2, 3, 2],
[2, 1, 4, 3],
[1/3, 1/4, 1, 1/2],
[1/2, 1/3, 2, 1]
])
print(f"Pairwise comparison matrix: \n {PCMr}\n")
# normalization
PCMr_norm = normalize_comparation(PCMr)
print(f"Normalized pairwise comparison matrix: \n {PCMr_norm}\n")
# calculate weight
Wr = weight(PCMr_norm)
print(f"Weight: {Wr}\n")
# check weight validity
validity_check(PCMr,Wr)

=== Reliability ===
Pairwise comparison matrix: 
 [[1.         0.5        3.         2.        ]
 [2.         1.         4.         3.        ]
 [0.33333333 0.25       1.         0.5       ]
 [0.5        0.33333333 2.         1.        ]]

Normalized pairwise comparison matrix: 
 [[0.26086957 0.24       0.3        0.30769231]
 [0.52173913 0.48       0.4        0.46153846]
 [0.08695652 0.12       0.1        0.07692308]
 [0.13043478 0.16       0.2        0.15384615]]

Weight: [0.27714047 0.4658194  0.0959699  0.16107023]

CV: [4.04163398 4.05133544 4.01521752 4.01597107]

Eigen: 4.03103950215422

RI: 0.9

CI: 0.010346500718073415

CR: 0.011496111908970461

Weight is valid!



In [31]:
print("=== Fuel Economy ===")
# pairwise comparison matrix of fuel economy for each alternative
# order: yamaha, honda, suzuki, kawasaki
PCMe= np.array([
[1, 60/80, 1, 60/80],
[80/60, 1, 80/60, 1],
[1, 60/80, 1, 60/80],
[80/60, 1, 80/60, 1]
])
print(f"Pairwise comparison matrix: {PCMe}\n")
# normalization
PCMe_norm = normalize_comparation(PCMe)
print(f"Normalized pairwise comparison matrix: {PCMe_norm}\n")
# calculate weight
We = weight(PCMe_norm)
print(f"Weight: {We}\n")
# check weight validity
validity_check(PCMe,We)

=== Fuel Economy ===
Pairwise comparison matrix: [[1.         0.75       1.         0.75      ]
 [1.33333333 1.         1.33333333 1.        ]
 [1.         0.75       1.         0.75      ]
 [1.33333333 1.         1.33333333 1.        ]]

Normalized pairwise comparison matrix: [[0.21428571 0.21428571 0.21428571 0.21428571]
 [0.28571429 0.28571429 0.28571429 0.28571429]
 [0.21428571 0.21428571 0.21428571 0.21428571]
 [0.28571429 0.28571429 0.28571429 0.28571429]]

Weight: [0.21428571 0.28571429 0.21428571 0.28571429]

CV: [4. 4. 4. 4.]

Eigen: 4.0

RI: 0.9

CI: 0.0

CR: 0.0

Weight is valid!



In [33]:
# gather the weights of all criteria in one matrix
W_total = np.array([Ws, Wr, We])
# calculate final weight
W_final = final_weight(W_total, Wc)
print(f"Bobot akhir: {W_final}\n")
# display the best alternative
max_index = np.argmax(W_final)
print(f"The best alternative is {A[max_index]} with final weight of {W_final[max_index]}")

Bobot akhir: [0.23226317 0.3833129  0.11047767 0.27394626]

The best alternative is Honda with final weight of 0.3833128995745455
